### ISSUE TITLE
Minor updates to varscoper grammar

### ISSUE THREAD

**Issue by ian-a-hickey** [owenallenaz/CfscriptVarscoper#1]
I made some minor updates to the varscoper grammar to fix some issues I was having. I can't seem to submit a pull request however. Are you accepting pull requests for review to this project?

**Comment by ryaneberly** [comment]
Ian,
   Sorry for the chiming in on a slightly different note.  It popped on my feed.

   There is a more robust cfscript/cfml antlr4 grammar/parser here:
https://github.com/cfparser/cfparser 
and a linter (including varscoper) based on it, here:
https://github.com/cflint/CFLint

   It is active, and there are a couple contributors, though the community is still pretty small.

   FYI.

**Comment by owenallenaz** [comment]
If @ryaneberly's suggestion is accurate I would definitely advise looking into that. I haven't been active in CF for a few years now, I've moved on to Node. This was a side experiment to learn about lexers and parsers so it's not being actively maintained or used in any fashion.

**Comment by ian-a-hickey** [comment]
I'll definitely check it out @ryaneberly, thanks. It being actively maintained is a huge plus. @owenallenaz Your CFScript grammar is pretty small, but works well for the small custom tools I've been building with it (adding doc comments to source files, generating YAML etc) to learn more about ANTLR4. Thanks.
